# Generated by Django 5.1.7 on 2025-04-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='contacto_emergencia',
            field=models.BooleanField(default=False),
        ),
    ]
