# Generated by Django 5.1.7 on 2025-04-19 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0002_contacto_contacto_emergencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='contacto_emergencia',
        ),
    ]
