# Generated by Django 5.1.7 on 2025-04-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0004_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='fotos_perfil/default.png', upload_to='fotos_perfil/'),
        ),
    ]
