# Generated by Django 5.1.7 on 2025-04-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0005_rename_user_perfil_usuario_alter_perfil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_contactos/'),
        ),
    ]
