# Generated by Django 5.1.7 on 2025-04-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0006_contacto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
