# Generated by Django 5.1.7 on 2025-04-25 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0007_alter_contacto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='foto',
        ),
    ]
